name: CI_hse_tp_hw
on:
  push:
    branches: "*" 
  workflow_dispatch: 


jobs:
  first_tg:
    name: first_tg_not
    runs-on: ubuntu-latest
    steps:
    - name: Tg_send_test_new        
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }} 
  
  tests_main:
    name: tests_main
    runs-on: ubuntu-latest
    needs: first_tg
    steps:
      - name: Tests_Main
        uses: actions/checkout@v3.1.0
      - run: python3 -m unittest tests_main.Tests &> output.txt
      - name: run tests
        uses: mathiasvr/command-output@v1.1.0
        id: tst_main
        with:
          run: cat output.txt
            
      - name: Tg_send_tests_main
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Тесты основные:
            ${{ job.status }}
            ${{ steps.tst_main.outputs.stdout }}
 
    
      
 
  test_new:
    name: Tests_Main
    runs-on: ubuntu-latest
    needs: first_tg
    steps:
      - name: Test_New
        uses: actions/checkout@v3.1.0
      - run: |
          cd ${{ github.workspace }}
          python3 -m unittest new_test.TestNew
      - name: Tg_send_test_new    
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Новый тест:
            ${{ job.status }}
  test_speed:
    name: Test_Speed
    runs-on: ubuntu-latest
    needs: first_tg
    steps:
      - name: Test_Speed
        uses: actions/checkout@v3.1.0
      - run: |
          cd ${{ github.workspace }}
          pip install matplotlib
          python3 -m unittest test_speed.py

      - name: Tg_send_test_new        
        if: ${{ always() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            тест скорости:
            ${{ job.status }}
 
        


