# This is a basic workflow to help you get started with Actions

name: CI_hse_tp_hw
on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  testings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: fs_cr
        run: echo Hello, world!
        
  tg_not:
    uses: yanzay/notify-telegram@v0.1.0
    with:
      chat: '@Nonsonsoman' 
      token: '5649581220:AAHqcdXgpQn4yzbcNfdg6EIzvUgap790RzQ'
      status: 'fdfd'
