name: CI_hse_tp_hw
on:
  push:
    branches: [ "main" ]


jobs:
  test_main:
    name: tests_main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests_Main
      - run: |
          git clone https://github.com/Nonsensens/hse_tp_hw_2.git
          python3 -m unittest tests_main.Tests
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Тесты основные:
            ${{ job.status }
 
      
 
  test_new:
    name: test_new
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test_New
      - run: |
          git clone https://github.com/Nonsensens/hse_tp_hw_2.git
          python3 -m unittest new_test.TestNew
          ls
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Новый тест:
            ${{ job.status }
          
  tg_not:
    runs-on: ubuntu-latest
    name: tg_noti_no
    steps:
      - name: send tg noti
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ job.status }}

        


