# This is a basic workflow to help you get started with Actions

name: CI_hse_tp_hw
on:
  push:
    branches: [ "main" ]


jobs:
  test_main:
    name: tests_main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tests_Main
        run: |
          git clone https://github.com/Nonsensens/hse_tp_hw_2.git
          python3 -m unittest tests_main.Tests
 
  test_new:
    name: test_new
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test_New
        run: |
          git clone https://github.com/Nonsensens/hse_tp_hw_2.git
          python3 -m unittest new_test.TestNew
          
  tg_not:
    runs-on: ubuntu-latest
    name: tg_noti_no
    steps:
      - name: send tg noti
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

        


