# This is a basic workflow to help you get started with Actions

name: CI_hse_tp_hw
on:
  push:
    branches: [ "main" ]


jobs:
  testings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: fs_cr
        run: echo Hello, world!
  tg_not:
    runs-on: ubuntu-latest

    steps:
      - name: send tg noti
        uses: appleboy/telegram-action@0.0.3
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

        

